"""Add technology relationships

Revision ID: 284de66eb10c
Revises: 
Create Date: 2025-02-24 20:00:06.365225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284de66eb10c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new table with the correct schema
    op.create_table(
        'technology_versions_new',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('technology_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('end_of_life_date', sa.Date(), nullable=True),
        sa.Column('is_default', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name='fk_technology_versions_technology_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('technology_id', 'version', name='uq_tech_version_technology')
    )

    # Drop the old table and rename the new one
    op.drop_table('technology_versions')
    op.rename_table('technology_versions_new', 'technology_versions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new table with the old schema
    op.create_table(
        'technology_versions_old',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tech_stack_id', sa.Integer(), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('release_date', sa.Date(), nullable=True),
        sa.Column('end_of_life_date', sa.Date(), nullable=True),
        sa.Column('is_default', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(), default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), default=sa.func.now(), onupdate=sa.func.now()),
        sa.ForeignKeyConstraint(['tech_stack_id'], ['tech_stacks.id'], name='fk_technology_versions_tech_stack_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tech_stack_id', 'version', name='uq_tech_version')
    )

    # Drop the new table and rename the old one
    op.drop_table('technology_versions')
    op.rename_table('technology_versions_old', 'technology_versions')

    # ### end Alembic commands ###
