"""Add unique constraint on technology name and type

Revision ID: 58b0c268e3ed
Revises: 284de66eb10c
Create Date: 2025-02-24 20:07:06.502827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b0c268e3ed'
down_revision = '284de66eb10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_technology_name_type', ['name', 'type_id'])

    with op.batch_alter_table('technology_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tech_version_technology', type_='unique')
        batch_op.create_unique_constraint('uq_tech_version', ['technology_id', 'version'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technology_versions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tech_version', type_='unique')
        batch_op.create_unique_constraint('uq_tech_version_technology', ['technology_id', 'version'])

    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.drop_constraint('uq_technology_name_type', type_='unique')

    # ### end Alembic commands ###
